// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"CustomLogo","status":true,"description":"Shows RPG Maker and user logos at the start of the game.","parameters":{"logo1":"","logo1ImageName":"MadeWithMv","logo1Skippable":"true","logo1Coordinate":"","logo1X":"408","logo1Y":"312","logo1Origin":"0.5","logo1Time":"","logo1FadeinFrames":"12","logo1FadeoutFrames":"12","logo1DurationFrames":"120","logo2":"","logo2ImageName":"","logo2Skippable":"true","logo2Coordinate":"","logo2X":"408","logo2Y":"312","logo2Origin":"0.5","logo2Time":"","logo2FadeinFrames":"12","logo2FadeoutFrames":"12","logo2DurationFrames":"120","logo3":"","logo3ImageName":"","logo3Skippable":"true","logo3Coordinate":"","logo3X":"408","logo3Y":"312","logo3Origin":"0.5","logo3Time":"","logo3FadeinFrames":"12","logo3FadeoutFrames":"12","logo3DurationFrames":"120","allowTotalSkip":"true"}},
{"name":"LiuYue_GainItemTips","status":true,"description":"v1.02 LiuYue_GainItemTips 获取道具显示","parameters":{"---插件---":"","IsPluginEnable":"true","---窗口---":"","WindowOfx":"0","WindowOfy":"0","WindowW":"300","LineNum":"1","WindowShowFrame":"40","WindowOpacity":"255","WindowFontSize":"20","WindowOpenSpeed":"32","WindowBkPic":"","BkOpFollowOpenSpeed":"true","BasePos":"right-top","---金币---":"","IsGoldShow":"true","AddGFormat":"获得金币","SubGFormat":"失去金币","GTextColor":"#ffffff","GIconID":"0","GSERank":"0","GLRank":"0","---图标---":"","IconScale":"1","IsIconFlash":"true","IconFlashFrame":"10","---文本---":"","AddFormat":"+ %1","SubFormat":"- %1","NumberFormat":"x %1","---音效---":"","EarnSound":"item","EarnVolume":"100","EarnPitch":"100","EarnBGSPan":"0","GSound":"Coin","GVolume":"100","GPitch":"100","GBGSPan":"0"}},
{"name":"SimpleMenuLayout_dsmodi","status":true,"description":"简单菜单屏幕系统 (支持角色变量切换背景 + 强制默认尺寸)","parameters":{"----Basic Settings----":"","MenuWidth":"120","MenuCols":"1","MenuXPosition":"{\"basis\":\"left\",\"correction\":\"50\"}","MenuYPosition":"{\"basis\":\"top\",\"correction\":\"0\"}"}},
{"name":"MrTS_NoItemCategories","status":true,"description":"MrTS移除物品分类栏[v1.1]","parameters":{"Hide Menu":"true","Hide Shop":"true"}},
{"name":"KJ_Puzzle","status":true,"description":"My Try.","parameters":{"CancelText":"重来","CancelEnable":"true","SwitchId":"12","ColNumber":"3","TotalNumber":"9","PicName":"Pic1","PicWidth":"600","PicHeight":"600"}},
{"name":"KMS_SaveWithSnap","status":true,"description":"[v0.1.0] Add captured image on save/load scene.","parameters":{"Image scale":"0.15","Enable JPEG":"1"}},
{"name":"ULDS","status":true,"description":"Unlimited Layer Display System.","parameters":{"Default Path":"parallaxes","Default Z":"0.5"}},
{"name":"MKR_PlayerMoveForbid","status":true,"description":"(v1.0.5) 玩家禁止移动","parameters":{"Default_Move_Flag":"200","Default_Menu_Flag":"true","Enter Flag":"true"}},
{"name":"YZ_yuyan_qiehuan","status":true,"description":"语言切换.","parameters":{}},
{"name":"YZ_Language_china","status":true,"description":"语言文本.","parameters":{}},
{"name":"YZ_Language_ENG","status":true,"description":"语言文本.","parameters":{}},
{"name":"YZ_export","status":false,"description":"工程文本导出.","parameters":{}},
{"name":"YED_WordWrap_DSmodi2","status":true,"description":"YED文本自动换行功能（智能换行 + 中英文不同字号）","parameters":{"Break Word":"true","Chinese Font Size":"24","English Font Size":"20"}},
{"name":"SmartPath_DSmodi","status":true,"description":"智能寻路事件追逐 (增强版：避开事件障碍 + 允许绕路)","parameters":{}},
{"name":"OggOnly","status":true,"description":"Use only ogg files to play the audio.","parameters":{"deleteM4a":"false"}},
{"name":"TitleCommandPosition","status":true,"description":"Changes the position of the title command window.","parameters":{"Offset X":"250","Offset Y":"50","Width":"150","Background":"2"}},
{"name":"loadingchange2","status":true,"description":"随机加载图","parameters":{}},
{"name":"LoadingOverlay","status":false,"description":"全局加载图（过场图覆盖）","parameters":{}},
{"name":"YZ_pintu","status":true,"description":"拼图系统.","parameters":{"拼图胜利开关ID":"55","胜利播放动画ID":"44"}},
{"name":"MOG_CharacterShadow","status":true,"description":"MOG角色阴影显示[v1.0]","parameters":{"X-Axis":"0","Y-Axis":"-4","Shadow File Name":"Shadow1","Auto Shadow (Events)":"false"}},
{"name":"YEP_SaveEventLocations","status":true,"description":"v1.06 Enable specified maps to memorize the locations of\nevents when leaving and loading them upon reentering map.","parameters":{}},
{"name":"PY_AutoSave","status":true,"description":"[v1.5]自动存档","parameters":{"存档位置":"20","调整光标位置":"true","存档文本":"自动存档/autosave","自动存档文本颜色":"6","存档音效":"","音效音量":"50","提示图片":"","提示图片ID":"1","提示图片x坐标":"10","提示图片y坐标":"10","提示图片透明度":"150","提示图片提示时间":"1"}},
{"name":"YZ_TitleLanguageSwitch","status":true,"description":"v1.0 根据当前语言动态切换标题画面图片","parameters":{"chineseTitleImage":"Title_CN","englishTitleImage":"Title_EN"}}
];
